# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

julia:
  - 1.0
  - nightly

matrix:
  exclude:
    - os: osx
      julia: nightly

    - os: windows
      julia: nightly
      language: julia

  include:
    - os: osx

    - os: windows
      language: sh
      before_install:
        - choco install julia
        - julia --color=yes -e 'using Pkg; pkg"dev ."; pkg"precompile"'


script:
  -                 julia --color=yes --project=. -e 'using Pkg; Pkg.test()'
  - JIVE_PROCS=auto julia --color=yes --project=. -e 'using Pkg; Pkg.test()'
  - cd test
  - julia --color=yes        runtests.jl
  - julia --color=yes        runtests.jl jive/s
  - julia --color=yes        runtests.jl jive/s jive/m start=2
  - julia --color=yes -pauto runtests.jl jive/s jive/m start=2
  - julia --color=yes        -e 'using Jive; runtests(@__DIR__, skip=["jive/onlyonce/heavy.jl", "jive/s", "jive/I"])'
  - julia --color=yes -pauto -e 'using Jive; runtests(@__DIR__, skip=["jive/onlyonce/heavy.jl", "jive/s"], node1=["jive/m"])'

after_success:
  - if [[ "$TRAVIS_OS_NAME" == linux && "$TRAVIS_JULIA_VERSION" == nightly ]] ; then julia --project=. -e 'using Pkg;
                                                                                                           Pkg.add("Coverage");
                                                                                                           using Coverage;
                                                                                                           Codecov.submit(process_folder())' ; fi
