desc = "some useful steps in tests"
keywords = ["test"]
license = "MIT"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
name = "Jive"
uuid = "6ea17500-d18f-11e8-3cf5-7930f07cb877"
version = "0.1.0"

[compat]
julia = "1.0.2"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
